version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: todo_mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: tododb
    ports:
      - '3306:3306'
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  mysql_data:
